M48
; DRILL file {KiCad 7.0.11} date Tuesday, November 18, 2025 at 10:52:37 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-18T22:52:37-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2165Y3.0433
X0.2165Y0.2323
X3.0039Y3.0433
X3.0118Y0.2323
M30
