M48
; DRILL file {KiCad (6.0.7-1)-1} date Wednesday, February 15, 2023 at 10:08:58 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-15T22:08:58-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2717Y3.0197
X0.2717Y0.2323
X3.0669Y3.0197
X3.0669Y0.2323
T0
M30
