M48
; DRILL file {KiCad 7.0.11} date Tuesday, September 17, 2024 at 09:56:22 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-17T21:56:22-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2165Y3.0039
X0.2165Y0.2165
X3.0118Y3.0039
X3.0118Y0.2165
M30
