M48
; DRILL file {KiCad 7.0.11} date Monday, February 03, 2025 at 10:53:57 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-03T22:53:57-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2008Y3.0157
X0.2008Y0.2283
X2.9961Y3.0157
X2.9961Y0.2283
M30
