M48
; DRILL file {KiCad (6.0.7-1)-1} date Tuesday, November 22, 2022 at 03:04:40 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-22T15:04:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2717Y3.0197
X0.2795Y0.2087
X3.0669Y3.0197
X3.0669Y0.2087
T0
M30
