M48
; DRILL file {KiCad 7.0.11} date Thursday, February 06, 2025 at 10:33:18 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-06T22:33:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.199Y3.0445
X0.199Y0.2335
X2.9864Y3.0445
X2.9943Y0.2335
M30
