M48
; DRILL file {KiCad 7.0.11} date Saturday, November 30, 2024 at 10:11:05 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-30T22:11:05-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2008Y3.0394
X0.2008Y0.2283
X2.9882Y3.0394
X2.9961Y0.2283
M30
