M48
; DRILL file {KiCad 7.0.11} date Sunday, February 23, 2025 at 07:16:26 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-23T19:16:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.2008Y3.0394
X0.2008Y0.2283
X2.9882Y3.0394
X2.9961Y0.2283
M30
